name: prevue-guide
services:
    test:
        ports:
            - 80:80      # HTTP HLS Port
            - 1935:1935  # RTMP Port
            - 5901:5901  # VNC Port
        volumes:
            - ./PREVUE.ADF:/app/prevue.adf:ro
            - ./KS204.rom:/app/ks.rom:ro
            - ./music/:/app/music:ro

            # For Time Sync. Ostensibly safe to leave completely alone.
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
        tmpfs:
            # Highly recommended RAM Disks to avoid unnecessary wear on your storage
            - /app/work:size=64M
            - /root/FS-UAE/Cache/Logs:size=64M
        environment:
            # ErsatzTV or other XML Source location to pull from.
            - XMLTV_LOCATION=http://YOUR_XMLTV_PATH_HERE/xmltv.xml
            # Your VNC Password of choice. Change it you nimrod.
            - VNC_PASSWD=hunter2
        stdin_open: true
        tty: true
        image: prevue:latest
